#pragma once

enum class AnimationName {
	DEFAULT,
	SHIP_HEALTHY,
	SHIP_DAMAGED_1,
	SHIP_DAMAGED_2,
	SHIP_DESTROYED,
	FLYING_CREW_MEMBER_1,
	FLYING_CREW_MEMBER_2,
	FLYING_CREW_MEMBER_3,
	FLYING_CREW_MEMBER_4,
	FLYING_CREW_MEMBER_5,
	FLYING_CREW_MEMBER_6,
};