#pragma once

enum class AnimationGroupName {
	SHIP_BLACK,
	SHIP_BLUE,
	SHIP_GREEN,
	SHIP_RED,
	SHIP_WHITE,
	SHIP_YELLOW,
	PROJECTILE_CANNON_BALL,
	PARTICLE_EXPLOSION,
	PARTICLE_CANNON_BALL_TRAIL,
	PARTICLE_WATER_SPLASH,
	PARTICLE_FLYING_CREW_MEMBER,
};